Logica para converter kelvin para celsius
felipetio/jacutinga-dev pull request #1
Opened 2024-12-17 14:35 UTC by YasGraciano

Novo módulo para converter temperatura em celsius com funções

2024-12-17 14:41 UTC, felipetio commented on conversor.py
> +def fahrenheit_para_celsius(fahrenheit):
@YasGraciano vamos lembrar de usar os types hints pois são uma boa prática de desenvolvimento em python :)

2024-12-17 14:41 UTC, felipetio commented on weather.py
> +    data_str = "2024-10-01"
O que tem a ver essa modificação com a conversão de temperatura?

2024-12-17 14:45 UTC, felipetio requested changes
Precisamos corrigir os types hints das novas funções.

2025-01-13 19:22 UTC, YasGraciano commented on weather.py
> +    data_str = "2024-10-01"
Fiz uma modificação para corrigir os dados da data. A data anterior estava no futuro, o que prejudicava o funcionamento do código.

2025-01-14 13:52 UTC, YasGraciano commented on conversor.py
> +def fahrenheit_para_celsius(fahrenheit):
Alterações realizadas

2025-01-14 13:54 UTC, felipetio approved these changes
Parabéns pelo seu primeiro PR. Orgulho!

2025-01-14 13:55 UTC, merged